spring:
  application:
    name: inventory-tracking-accounting
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    app.inv: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt-secret: "inventory-tracking-accounting-secret-key-change-in-production"
  jwt-expiration: 86400

# Flyway配置
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
